name: Markdown formatting

on:
  push:
    branches:
      - main
    paths:
      - "**/*.md"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "**/*.md"

permissions:
  contents: read

jobs:
  markdownlint:
    name: Check Markdown formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: .devops/markdown-format/package.json

      - name: Install Markdown lint dependencies
        shell: bash
        run: npm install --prefix .devops/markdown-format

      - name: Lint Markdown files
        shell: bash
        run: |
          .devops/markdown-format/node_modules/.bin/markdownlint-cli2 \
            --config .markdownlint.yaml \
            "**/*.md" \
            "#./**/node_modules"
